# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

SEVIRI :
  type : obs
  filenames : ['observations-file-2018-2019-seviri-h512-v1.zarr']
  loss_weight : 1.
  # masking_rate_none : 0.05
  token_size : 1024
  # max_num_targets: 8192
  embed :
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 8
  pred_head :
    ens_size : 1
    num_layers : 1