[project]
name = "weathergen-evaluate"
version = "1.0"
description = "The WeatherGenerator Machine Learning Earth System Model"
readme = "./README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "seaborn", 
    "cartopy>=0.24.1",
    "xskillscore",
    "xhistogram",
    "panel",
    "omegaconf",
    "plotly>=6.2.0",
    "weathergen-common",
    "weathergen-metrics",
    "eccodes==2.44.0", 
    "eccodeslib==2.44.0.7", 
    "eckitlib==1.32.3.7", 
    "earthkit-data==0.18.2"
]

[dependency-groups]
dev = [
 "pytest~=8.3.5",
 "pytest-mock>=3.14.1",
 "ruff==0.9.7",
 "pyrefly==0.36.0",
]

[project.scripts]
evaluation = "weathergen.evaluate.run_evaluation:evaluate"
export = "weathergen.evaluate.export.export_inference:export"

# The linting configuration
[tool.ruff]
extend = "../../pyproject.toml"

[tool.pyrefly]
project-includes = ["src/"]
project-excludes = [
]

[tool.pyrefly.errors]
bad-argument-type = false
unsupported-operation = false
missing-attribute = false
no-matching-overload = false

# To do:
bad-assignment = false
bad-return = false
index-error = false
not-iterable = false
not-callable = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/weathergen"]


