name: CI

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:
  linting:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.13"

      - name: Run ruff (black)
        # Do not attempt to install the default dependencies, this is much faster.
        # Run temporarily on a sub directory before the main restyling.
        run: ./scripts/actions.sh lint-check

      - name: Type checker (pyrefly, experimental)
        # Do not attempt to install the default dependencies, this is much faster.
        # Run temporarily on a sub directory before the main restyling.
        run: ./scripts/actions.sh type-check-experimental || echo "::warning::typing issues found"
  pr:
    name: PR checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.13"

      - name: Check PR is linked to an issue
      # Send the PR number to the script, which will check if it is linked to an issue.
        run: scripts/check_gh_issue.py $GITHUB_REF_NAME
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.13"

      - name: Run all unit tests
      # Send the PR number to the script, which will check if it is linked to an issue.
        run: ./scripts/actions.sh unit-test
